apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
  labels:
{{- toYaml .Values.labels | nindent 4}}
spec:
  type: {{.Values.service.type}}
  selector:
{{- toYaml .Values.labels | nindent 4}}
  ports:
  - port: {{ .Values.service.port}}
